/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizGUI;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author jdani
 */
public class Pregunta3 extends javax.swing.JFrame {

    /**
     * Creates new form PrimeraPregunta
     */
    int respondidas = 0;
    int puntaje = 0;
    
    public Pregunta3(int Respondidas, int Puntaje) {
        initComponents();
        this.respondidas = Respondidas;
        this.puntaje = Puntaje;
        
        this.setLocationRelativeTo(this);  //iniciamos el programa en el centro de la pantalla
        setIconImage(new ImageIcon(getClass().getResource("paletaIcon.png")).getImage()); //Para poner el icono que queramos
        
        SetImageLabel(jLblimagen, "src/quizGUI/SagradaFamilia.jpg"); //usamos el método para meter una imagen al JLabel
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLblPrimeraPregunta = new javax.swing.JLabel();
        jLbl1Pregunta = new javax.swing.JLabel();
        jLblimagen = new javax.swing.JLabel();
        jRBIncorrecta1 = new javax.swing.JRadioButton();
        jRBIncorrecta2 = new javax.swing.JRadioButton();
        jRBIncorrecta3 = new javax.swing.JRadioButton();
        jRBCorrecta = new javax.swing.JRadioButton();
        jButtonComprobar = new javax.swing.JButton();
        jButtonContinuar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLblMostrarRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLblPrimeraPregunta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLblPrimeraPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPrimeraPregunta.setText("C");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLblPrimeraPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblPrimeraPregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLbl1Pregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbl1Pregunta.setText("¿Cómo se llama la obra arquitectónica?");

        jLblimagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(jRBIncorrecta1);
        jRBIncorrecta1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRBIncorrecta1.setText("Santa Familia");
        jRBIncorrecta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIncorrecta1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBIncorrecta2);
        jRBIncorrecta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRBIncorrecta2.setText("Familia Santa");

        buttonGroup1.add(jRBIncorrecta3);
        jRBIncorrecta3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRBIncorrecta3.setText("Sagris Familis");

        buttonGroup1.add(jRBCorrecta);
        jRBCorrecta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRBCorrecta.setText("Sagrada Familia");

        jButtonComprobar.setBackground(new java.awt.Color(255, 255, 0));
        jButtonComprobar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonComprobar.setText("COMPROBAR RESPUESTA");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        jButtonContinuar.setBackground(new java.awt.Color(255, 255, 0));
        jButtonContinuar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonContinuar.setText("ENVIAR Y CONTINUAR");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESPUESTA: ");

        jLblMostrarRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblMostrarRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblMostrarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblMostrarRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLbl1Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBIncorrecta3)
                            .addComponent(jRBCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBIncorrecta1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonComprobar))
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jRBIncorrecta1)
                        .addGap(18, 18, 18)
                        .addComponent(jRBCorrecta)
                        .addGap(18, 18, 18)
                        .addComponent(jRBIncorrecta2)
                        .addGap(18, 18, 18)
                        .addComponent(jRBIncorrecta3)
                        .addGap(128, 128, 128)
                        .addComponent(jButtonComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLbl1Pregunta)
                        .addGap(39, 39, 39)
                        .addComponent(jLblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBIncorrecta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIncorrecta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBIncorrecta1ActionPerformed

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
        // TODO add your handling code here:
        //Aquí decimos que si en caso que no se selecciona ninguna respuesta, saldrá una ventana JOptionPane que dice que selecciones una respuesta obligatoriamente
        if(!jRBIncorrecta1.isSelected() && !jRBIncorrecta2.isSelected() && !jRBIncorrecta3.isSelected() && !jRBCorrecta.isSelected()){
            JOptionPane.showMessageDialog(null, "Selecciona una respuesta");
        } else{
            //Aquí mostramos en un JLabel si la respuesta seleccionada es correcta o incorrecta
            if(jRBCorrecta.isSelected()){
                jLblMostrarRespuesta.setText("CORRECTA!!");
                jLblMostrarRespuesta.setForeground(Color.green);
            } else{
                jLblMostrarRespuesta.setText("INCORRECTA :( ");
                jLblMostrarRespuesta.setForeground(Color.red);
            }
            //Cuando seleccionamos una respuesta y queremos ver si es correcta o incorrecta, nos deja seleccionar otra respuesta y volver a comprobar la respuesta,
            //por eso aquí vamos a bloquear las demás respuestas una vez que ya seleccionamos una respuesta.
            jRBIncorrecta1.setEnabled(false);
            jRBIncorrecta2.setEnabled(false);
            jRBIncorrecta3.setEnabled(false);
            jRBCorrecta.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
        if(!jRBIncorrecta1.isSelected() && !jRBIncorrecta2.isSelected() && !jRBIncorrecta3.isSelected() && !jRBCorrecta.isSelected()){
            JOptionPane.showMessageDialog(null, "Selecciona una respuesta");
        } else{
            if(jRBCorrecta.isSelected()){
                //asignamos 5 puntos a la variable puntaje
                puntaje = puntaje + 5;
            //asignamos la pregunta respondida
            respondidas = respondidas +1;            
            }
            //pasamos a la siguiente pregunta
            new Pregunta4(respondidas, puntaje).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta3(0,0).setVisible(true);
            }
        });
    }
    
    //método para agregar imagen a un JLabel 
    private void SetImageLabel(JLabel labelName, String ruta){
        ImageIcon image = new ImageIcon(ruta);
        Icon icon = new ImageIcon(
                    image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbl1Pregunta;
    private javax.swing.JLabel jLblMostrarRespuesta;
    private javax.swing.JLabel jLblPrimeraPregunta;
    private javax.swing.JLabel jLblimagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBCorrecta;
    private javax.swing.JRadioButton jRBIncorrecta1;
    private javax.swing.JRadioButton jRBIncorrecta2;
    private javax.swing.JRadioButton jRBIncorrecta3;
    // End of variables declaration//GEN-END:variables
}
